package io.github.maliciousfiles.bloodOnTheClocktower.lib;

import com.google.common.collect.ImmutableMap;
import io.github.maliciousfiles.bloodOnTheClocktower.lib.roles.Poisoner;
import io.github.maliciousfiles.bloodOnTheClocktower.lib.roles.Washerwoman;
import org.bukkit.Material;

import javax.annotation.Nullable;
import java.util.Map;
import java.util.concurrent.ExecutionException;

public abstract class Role {
    public enum Type { TOWNSFOLK, OUTSIDER, MINION, DEMON, TRAVELLER }

    public static final Map<String, Class<? extends Role>> BY_ID = new ImmutableMap.Builder<String, Class<? extends Role>>()
            .put("poisoner", Poisoner.class)
            .put("washerwoman", Washerwoman.class)
            // temp, to test TB
            .put("chef", Poisoner.class)
            .put("empath", Poisoner.class)
            .put("fortuneteller", Poisoner.class)
            .put("investigator", Poisoner.class)
            .put("librarian", Poisoner.class)
            .put("mayor", Poisoner.class)
            .put("monk", Poisoner.class)
            .put("ravenkeeper", Poisoner.class)
            .put("slayer", Poisoner.class)
            .put("soldier", Poisoner.class)
            .put("undertaker", Poisoner.class)
            .put("virgin", Poisoner.class)
            .put("drunk", Poisoner.class)
            .put("butler", Poisoner.class)
            .put("saint", Poisoner.class)
            .put("recluse", Poisoner.class)
            .put("scarletwoman", Poisoner.class)
            .put("spy", Poisoner.class)
            .put("baron", Poisoner.class)
            .put("imp", Poisoner.class)
            .put("beggar", Poisoner.class)
            .put("bureaucrat", Poisoner.class)
            .put("gunslinger", Poisoner.class)
            .put("scapegoat", Poisoner.class)
            .put("thief", Poisoner.class)
            .build();
    Map<String, Integer> CMD_IDs = new ImmutableMap.Builder<String, Integer>() // custom model data IDs
            .put("acrobat", 1)
            .put("alchemist", 2)
            .put("alsaahir", 3)
            .put("amnesiac", 4)
            .put("artist", 5)
            .put("atheist", 6)
            .put("balloonist", 7)
            .put("banshee", 8)
            .put("bountyhunter", 9)
            .put("cannibal", 10)
            .put("chambermaid", 11)
            .put("chef", 12)
            .put("choirboy", 13)
            .put("clockmaker", 14)
            .put("courtier", 15)
            .put("cultleader", 16)
            .put("dreamer", 17)
            .put("empath", 18)
            .put("engineer", 19)
            .put("exorcist", 20)
            .put("farmer", 21)
            .put("fisherman", 22)
            .put("flowergirl", 23)
            .put("fool", 24)
            .put("fortuneteller", 25)
            .put("gambler", 26)
            .put("general", 27)
            .put("gossip", 28)
            .put("grandmother", 29)
            .put("highpriestess", 30)
            .put("huntsman", 31)
            .put("innkeeper", 32)
            .put("investigator", 33)
            .put("juggler", 34)
            .put("king", 35)
            .put("knight", 36)
            .put("librarian", 37)
            .put("lycanthrope", 38)
            .put("magician", 39)
            .put("mathematician", 40)
            .put("mayor", 41)
            .put("minstrel", 42)
            .put("monk", 43)
            .put("nightwatchman", 44)
            .put("noble", 45)
            .put("oracle", 46)
            .put("pacifist", 47)
            .put("philosopher", 48)
            .put("pixie", 49)
            .put("poppygrower", 50)
            .put("preacher", 51)
            .put("professor", 52)
            .put("ravenkeeper", 53)
            .put("sage", 54)
            .put("sailor", 55)
            .put("savant", 56)
            .put("seamstress", 57)
            .put("shugenja", 58)
            .put("slayer", 59)
            .put("snakecharmer", 60)
            .put("soldier", 61)
            .put("steward", 62)
            .put("tealady", 63)
            .put("towncrier", 64)
            .put("undertaker", 65)
            .put("villageidiot", 66)
            .put("virgin", 67)
            .put("washerwoman", 68)
            .put("barber", 69)
            .put("butler", 70)
            .put("damsel", 71)
            .put("drunk", 72)
            .put("golem", 73)
            .put("goon", 74)
            .put("hatter", 75)
            .put("heretic", 76)
            .put("klutz", 77)
            .put("lunatic", 78)
            .put("moonchild", 79)
            .put("mutant", 80)
            .put("ogre", 81)
            .put("plaguedoctor", 82)
            .put("politician", 83)
            .put("puzzlemaster", 84)
            .put("recluse", 85)
            .put("saint", 86)
            .put("snitch", 87)
            .put("sweetheart", 88)
            .put("tinker", 89)
            .put("zealot", 90)
            .put("assassin", 91)
            .put("baron", 92)
            .put("boffin", 93)
            .put("boomdandy", 94)
            .put("cerenovus", 95)
            .put("devilsadvocate", 96)
            .put("eviltwin", 97)
            .put("fearmonger", 98)
            .put("goblin", 99)
            .put("godfather", 100)
            .put("harpy", 101)
            .put("marionette", 102)
            .put("mastermind", 103)
            .put("mezepheles", 104)
            .put("organgrinder", 105)
            .put("pithag", 106)
            .put("poisoner", 107)
            .put("psychopath", 108)
            .put("scarletwoman", 109)
            .put("spy", 110)
            .put("summoner", 111)
            .put("vizier", 112)
            .put("widow", 113)
            .put("witch", 114)
            .put("xaan", 115)
            .put("alhadikhia", 116)
            .put("fanggu", 117)
            .put("imp", 118)
            .put("kazali", 119)
            .put("legion", 120)
            .put("leviathan", 121)
            .put("lilmonsta", 122)
            .put("lleech", 123)
            .put("lordoftyphon", 124)
            .put("nodashii", 125)
            .put("ojo", 126)
            .put("po", 127)
            .put("pukka", 128)
            .put("riot", 129)
            .put("shabaloth", 130)
            .put("vigormortis", 131)
            .put("vortox", 132)
            .put("yaggababble", 133)
            .put("zombuul", 134)
            .put("scapegoat", 135)
            .put("gunslinger", 136)
            .put("beggar", 137)
            .put("bureaucrat", 138)
            .put("thief", 139)
            .put("butcher", 140)
            .put("bonecollector", 141)
            .put("harlot", 142)
            .put("barista", 143)
            .put("deviant", 144)
            .put("apprentice", 145)
            .put("matron", 146)
            .put("voudon", 147)
            .put("judge", 148)
            .put("bishop", 149)
            .put("gangster", 150)
            .put("doomsayer", 151)
            .put("angel", 152)
            .put("buddhist", 153)
            .put("hellslibrarian", 154)
            .put("revolutionary", 155)
            .put("fiddler", 156)
            .put("toymaker", 157)
            .put("fibbin", 158)
            .put("duchess", 159)
            .put("sentinel", 160)
            .put("spiritofivory", 161)
            .put("djinn", 162)
            .put("bootlegger", 163)
            .put("ferryman", 164)
            .put("gardener", 165)
            .put("stormcatcher", 166)
            .build();

    protected final BOTCPlayer me;
    protected final Game game;

    public Role(BOTCPlayer me, Game game) {
        this.me = me;
        this.game = game;
    }

    public abstract String getRoleName();
    public abstract String getRoleDescription();
    public abstract Material getIcon();
    public abstract Type getType();
    public abstract float getNightOrder(); // https://docs.google.com/spreadsheets/d/1eJkBC6rF-VU6J0h0KJvyiXjs2HLl6Yjzw9jfVYHOW34/edit

    public void setup() {}
    public void handleNight() throws InterruptedException, ExecutionException {}

    public enum DeathCause { STORY, EXECUTION, PLAYER }
    public void handleDeathAttempt(DeathCause cause, @Nullable BOTCPlayer killer) {
        me.die();
    }
}
